import type { EquipmentSlot, Item, StatId } from "../types";

type ItemInput = {
  id: string;
  name: string;
  slot: EquipmentSlot;
  tier: number;
  description: string;
  bonuses: Partial<Record<StatId, number>>;
  tags?: string[];
};

function createItem(input: ItemInput): Item {
  return {
    bonuses: input.bonuses,
    description: input.description,
    id: input.id,
    name: input.name,
    slot: input.slot,
    tags: input.tags,
    tier: input.tier,
  };
}

export const items: Item[] = [
  createItem({
    bonuses: { strength: 1 },
    description: "Iron plates fitted for direct force.",
    id: "iron_gauntlets",
    name: "Iron Gauntlets",
    slot: "weapon",
    tags: ["strength"],
    tier: 1,
  }),
  createItem({
    bonuses: { intellect: 1 },
    description: "A ring etched with patient mnemonic marks.",
    id: "scholar_ring",
    name: "Scholar Ring",
    slot: "trinket",
    tags: ["intellect"],
    tier: 1,
  }),
  createItem({
    bonuses: { agility: 1 },
    description: "Soft boots built for quiet footing.",
    id: "shadow_boots",
    name: "Shadow Boots",
    slot: "armor",
    tags: ["agility"],
    tier: 1,
  }),
  createItem({
    bonuses: { spirit: 1 },
    description: "A warm charm that steadies breath under pressure.",
    id: "ember_charm",
    name: "Ember Charm",
    slot: "trinket",
    tags: ["spirit"],
    tier: 1,
  }),
  createItem({
    bonuses: { agility: 1, intellect: 1 },
    description: "A practical cloak with hidden pockets and map-stitching.",
    id: "balanced_cloak",
    name: "Balanced Cloak",
    slot: "armor",
    tags: ["agility", "intellect", "mixed"],
    tier: 1,
  }),
  createItem({
    bonuses: { spirit: 1, strength: 1 },
    description: "A heavy cord worn by those who refuse to yield.",
    id: "oath_cord",
    name: "Oath Cord",
    slot: "trinket",
    tags: ["spirit", "strength", "mixed"],
    tier: 1,
  }),
  createItem({
    bonuses: { strength: 2 },
    description: "A blunt blade made for breaking guards and gates.",
    id: "breaker_blade",
    name: "Breaker Blade",
    slot: "weapon",
    tags: ["strength"],
    tier: 2,
  }),
  createItem({
    bonuses: { intellect: 2 },
    description: "A narrow lens that reveals stress lines and hidden joins.",
    id: "logic_lens",
    name: "Logic Lens",
    slot: "trinket",
    tags: ["intellect"],
    tier: 2,
  }),
  createItem({
    bonuses: { agility: 2 },
    description: "Light armor that turns sudden movement into protection.",
    id: "quickstep_vest",
    name: "Quickstep Vest",
    slot: "armor",
    tags: ["agility"],
    tier: 2,
  }),
  createItem({
    bonuses: { spirit: 2 },
    description: "A polished icon that stays warm in hostile places.",
    id: "resolve_icon",
    name: "Resolve Icon",
    slot: "trinket",
    tags: ["spirit"],
    tier: 2,
  }),
  createItem({
    bonuses: { intellect: 1, strength: 1 },
    description: "A fitted mail shirt with marked reinforcement points.",
    id: "engineer_mail",
    name: "Engineer Mail",
    slot: "armor",
    tags: ["intellect", "strength", "mixed"],
    tier: 2,
  }),
  createItem({
    bonuses: { agility: 1, spirit: 1 },
    description: "A pendant that helps its bearer move without panic.",
    id: "wind_prayer",
    name: "Wind Prayer",
    slot: "trinket",
    tags: ["agility", "spirit", "mixed"],
    tier: 2,
  }),
  createItem({
    bonuses: { strength: 3 },
    description: "A war hammer balanced for relentless pressure.",
    id: "warden_hammer",
    name: "Warden Hammer",
    slot: "weapon",
    tags: ["strength"],
    tier: 3,
  }),
  createItem({
    bonuses: { intellect: 3 },
    description: "A traveling codex of methods, proofs, and countersigns.",
    id: "living_codex",
    name: "Living Codex",
    slot: "trinket",
    tags: ["intellect"],
    tier: 3,
  }),
  createItem({
    bonuses: { agility: 3 },
    description: "A mantle that seems to choose the easiest path first.",
    id: "mist_mantle",
    name: "Mist Mantle",
    slot: "armor",
    tags: ["agility"],
    tier: 3,
  }),
  createItem({
    bonuses: { spirit: 3 },
    description: "A relic that quiets fear before it can take shape.",
    id: "lantern_relic",
    name: "Lantern Relic",
    slot: "trinket",
    tags: ["spirit"],
    tier: 3,
  }),
  createItem({
    bonuses: { agility: 2, strength: 1 },
    description: "A precise dueling weapon with unexpected stopping power.",
    id: "duelist_knife",
    name: "Duelist Knife",
    slot: "weapon",
    tags: ["agility", "strength", "mixed"],
    tier: 3,
  }),
  createItem({
    bonuses: { intellect: 2, spirit: 1 },
    description: "A silver circlet for calm judgment under supernatural pressure.",
    id: "sage_circlet",
    name: "Sage Circlet",
    slot: "trinket",
    tags: ["intellect", "spirit", "mixed"],
    tier: 3,
  }),
  createItem({
    bonuses: { strength: 4 },
    description: "A legendary edge that answers only decisive force.",
    id: "titan_edge",
    name: "Titan Edge",
    slot: "weapon",
    tags: ["strength"],
    tier: 4,
  }),
  createItem({
    bonuses: { intellect: 4 },
    description: "A crystal archive that assembles patterns as they appear.",
    id: "oracle_prism",
    name: "Oracle Prism",
    slot: "trinket",
    tags: ["intellect"],
    tier: 4,
  }),
  createItem({
    bonuses: { agility: 4 },
    description: "A seamless coat that never catches, drags, or hesitates.",
    id: "horizon_coat",
    name: "Horizon Coat",
    slot: "armor",
    tags: ["agility"],
    tier: 4,
  }),
  createItem({
    bonuses: { spirit: 4 },
    description: "An old star set in iron, still bright in the dark.",
    id: "star_heart",
    name: "Star Heart",
    slot: "trinket",
    tags: ["spirit"],
    tier: 4,
  }),
  createItem({
    bonuses: { intellect: 2, strength: 2 },
    description: "A weapon whose weight changes when its bearer understands it.",
    id: "calculated_maul",
    name: "Calculated Maul",
    slot: "weapon",
    tags: ["intellect", "strength", "mixed"],
    tier: 4,
  }),
  createItem({
    bonuses: { agility: 2, spirit: 2 },
    description: "Armor built for motion guided by instinct.",
    id: "moonstep_armor",
    name: "Moonstep Armor",
    slot: "armor",
    tags: ["agility", "spirit", "mixed"],
    tier: 4,
  }),
  createItem({
    bonuses: { strength: 1 },
    description: "A battered guard plate that turns the shoulder into a weapon.",
    id: "guard_buckler",
    name: "Guard Buckler",
    slot: "armor",
    tags: ["strength"],
    tier: 1,
  }),
  createItem({
    bonuses: { intellect: 1 },
    description: "A writing blade used to mark plans into wood, wax, and stone.",
    id: "cipher_quill",
    name: "Cipher Quill",
    slot: "weapon",
    tags: ["intellect"],
    tier: 1,
  }),
  createItem({
    bonuses: { agility: 1 },
    description: "A narrow dagger balanced for one clean opening.",
    id: "foxglass_dagger",
    name: "Foxglass Dagger",
    slot: "weapon",
    tags: ["agility"],
    tier: 1,
  }),
  createItem({
    bonuses: { spirit: 1 },
    description: "A plain travel mantle that keeps fear from spreading.",
    id: "pilgrim_mantle",
    name: "Pilgrim Mantle",
    slot: "armor",
    tags: ["spirit"],
    tier: 1,
  }),
  createItem({
    bonuses: { strength: 2 },
    description: "Layered plates built for holding ground under impact.",
    id: "bulwark_plate",
    name: "Bulwark Plate",
    slot: "armor",
    tags: ["strength"],
    tier: 2,
  }),
  createItem({
    bonuses: { intellect: 2 },
    description: "A command rod marked with battlefield timing notes.",
    id: "tactician_baton",
    name: "Tactician Baton",
    slot: "weapon",
    tags: ["intellect"],
    tier: 2,
  }),
  createItem({
    bonuses: { agility: 2 },
    description: "A hooked blade that rewards quick angles and clean exits.",
    id: "glasshook_blade",
    name: "Glasshook Blade",
    slot: "weapon",
    tags: ["agility"],
    tier: 2,
  }),
  createItem({
    bonuses: { spirit: 2 },
    description: "Quiet mail that turns each breath into renewed commitment.",
    id: "vowkeeper_mail",
    name: "Vowkeeper Mail",
    slot: "armor",
    tags: ["spirit"],
    tier: 2,
  }),
  createItem({
    bonuses: { strength: 3 },
    description: "A heavy harness that lets the whole body answer a challenge.",
    id: "giantbone_harness",
    name: "Giantbone Harness",
    slot: "armor",
    tags: ["strength"],
    tier: 3,
  }),
  createItem({
    bonuses: { intellect: 3 },
    description: "A scepter whose etched head preserves solved patterns.",
    id: "pattern_scepter",
    name: "Pattern Scepter",
    slot: "weapon",
    tags: ["intellect"],
    tier: 3,
  }),
  createItem({
    bonuses: { agility: 3 },
    description: "Twin climbing blades that make vertical routes feel level.",
    id: "skycutters",
    name: "Skycutters",
    slot: "weapon",
    tags: ["agility"],
    tier: 3,
  }),
  createItem({
    bonuses: { spirit: 3 },
    description: "A polished breastplate carried by those who refuse despair.",
    id: "saints_aegis",
    name: "Saint's Aegis",
    slot: "armor",
    tags: ["spirit"],
    tier: 3,
  }),
  createItem({
    bonuses: { strength: 4 },
    description: "A mantle weighted like a mountain and cut for those who can bear it.",
    id: "worldbreak_mantle",
    name: "Worldbreak Mantle",
    slot: "armor",
    tags: ["strength"],
    tier: 4,
  }),
  createItem({
    bonuses: { intellect: 4 },
    description: "A staff that turns final assumptions into visible structure.",
    id: "final_theorem_staff",
    name: "Final Theorem Staff",
    slot: "weapon",
    tags: ["intellect"],
    tier: 4,
  }),
  createItem({
    bonuses: { agility: 4 },
    description: "A needle blade that finds the space before an opening exists.",
    id: "phantom_needle",
    name: "Phantom Needle",
    slot: "weapon",
    tags: ["agility"],
    tier: 4,
  }),
  createItem({
    bonuses: { spirit: 4 },
    description: "A bright plate harness that makes retreat feel impossible.",
    id: "dawnward_plate",
    name: "Dawnward Plate",
    slot: "armor",
    tags: ["spirit"],
    tier: 4,
  }),
];
