#!/usr/bin/env bash
# Deploys Gravenhold to a Cartridge Slot Katana world and writes local Vite
# env values for testing the hosted world before a Vercel deployment.
#
# Required env vars:
#   SLOT_ACCOUNT_ADDRESS       Prefunded account for Slot migration.
#   SLOT_PRIVATE_KEY           Matching private key.
#
# Optional:
#   SLOT_NAME                  Cartridge Slot name. Defaults to gravenhold-slot.
#   RPC_URL                    Override Slot RPC URL.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
export PATH="$HOME/.asdf/shims:$PATH"

PROFILE="slot"
NAMESPACE="gravenhold"
SLOT_NAME="${SLOT_NAME:-gravenhold-slot}"
RPC_URL="${RPC_URL:-https://api.cartridge.gg/x/${SLOT_NAME}/katana}"
MANIFEST="$ROOT/manifest_slot.json"
DOJO_CONFIG="$ROOT/dojo_slot.toml"
CLIENT_ENV="$ROOT/.env.slot.local"
DOJO_CONFIG_BAK="$ROOT/.dojo_slot.toml.bak.$$"

restore_dojo_config() {
  if [[ -f "$DOJO_CONFIG_BAK" ]]; then
    mv "$DOJO_CONFIG_BAK" "$DOJO_CONFIG"
  fi
}
trap restore_dojo_config EXIT

info() { echo "[slot] $1"; }
fail() { echo "[slot] $1" >&2; }

command_or_asdf() {
  local name="$1"
  if command -v "$name" >/dev/null 2>&1; then
    printf '%s' "$name"
  else
    printf 'asdf exec %s' "$name"
  fi
}

SOZO_CMD="${SOZO_CMD:-$(command_or_asdf sozo)}"

if [[ -z "${SLOT_ACCOUNT_ADDRESS:-}" || -z "${SLOT_PRIVATE_KEY:-}" ]]; then
  fail "SLOT_ACCOUNT_ADDRESS and SLOT_PRIVATE_KEY must be set."
  fail "Get them with: slot deployments accounts ${SLOT_NAME} katana"
  exit 1
fi

for dep in jq curl perl; do
  if ! command -v "$dep" >/dev/null 2>&1; then
    fail "Required tool not found: $dep"
    exit 1
  fi
done

if [[ ! -f "$DOJO_CONFIG" ]]; then
  fail "$DOJO_CONFIG not found."
  exit 1
fi

cp "$DOJO_CONFIG" "$DOJO_CONFIG_BAK"
RPC_URL="$RPC_URL" \
SLOT_ACCOUNT_ADDRESS="$SLOT_ACCOUNT_ADDRESS" \
SLOT_PRIVATE_KEY="$SLOT_PRIVATE_KEY" \
  perl -0pi -e \
    's#(rpc_url\s*=\s*)"[^\"]+"#$1"$ENV{RPC_URL}"#s;
     s#(account_address\s*=\s*)"[^\"]+"#$1"$ENV{SLOT_ACCOUNT_ADDRESS}"#s;
     s#(private_key\s*=\s*)"[^\"]+"#$1"$ENV{SLOT_PRIVATE_KEY}"#s' \
    "$DOJO_CONFIG"

info "Building profile $PROFILE"
$SOZO_CMD build -P "$PROFILE"

info "Migrating to $RPC_URL"
$SOZO_CMD migrate -P "$PROFILE" \
  --rpc-url "$RPC_URL" \
  --account-address "$SLOT_ACCOUNT_ADDRESS" \
  --private-key "$SLOT_PRIVATE_KEY"

if [[ ! -f "$MANIFEST" ]]; then
  fail "$MANIFEST not generated by sozo migrate."
  exit 1
fi

WORLD=$(jq -r '.world.address // empty' "$MANIFEST")
ACTIONS=$(jq -r ".contracts[] | select(.tag == \"${NAMESPACE}-actions\") | .address" "$MANIFEST")

if [[ -z "$WORLD" || "$WORLD" == "null" || -z "$ACTIONS" || "$ACTIONS" == "null" ]]; then
  fail "Failed to extract world/actions from $MANIFEST."
  exit 1
fi

CHAIN_ID=$(curl -sf -X POST -H 'content-type: application/json' \
  --data '{"jsonrpc":"2.0","method":"starknet_chainId","params":[],"id":1}' \
  "$RPC_URL" | jq -r '.result // empty')

if [[ -z "$CHAIN_ID" || "$CHAIN_ID" == "null" ]]; then
  fail "Failed to read starknet_chainId from $RPC_URL."
  exit 1
fi

cat > "$CLIENT_ENV" <<EOF
# Generated by scripts/deploy_slot.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
VITE_STARKNET_RPC_URL=$RPC_URL
VITE_STARKNET_CHAIN_ID=$CHAIN_ID
VITE_ACCOUNT_MODE=wallet
VITE_DOJO_PROFILE=slot
VITE_DOJO_NAMESPACE=$NAMESPACE
VITE_DOJO_WORLD_ADDRESS=$WORLD
VITE_DOJO_ACTIONS_ADDRESS=$ACTIONS
VITE_SLOT_PROJECT=$SLOT_NAME
VITE_CONTROLLER_KEYCHAIN_URL=
EOF

info "Slot deploy complete"
echo "World:      $WORLD"
echo "Actions:    $ACTIONS"
echo "Chain ID:   $CHAIN_ID"
echo "Client env: $CLIENT_ENV"
echo ""
echo "Vercel env:"
echo "VITE_STARKNET_RPC_URL=$RPC_URL"
echo "VITE_STARKNET_CHAIN_ID=$CHAIN_ID"
echo "VITE_ACCOUNT_MODE=wallet"
echo "VITE_DOJO_PROFILE=slot"
echo "VITE_DOJO_NAMESPACE=$NAMESPACE"
echo "VITE_DOJO_WORLD_ADDRESS=$WORLD"
echo "VITE_DOJO_ACTIONS_ADDRESS=$ACTIONS"
echo "VITE_SLOT_PROJECT=$SLOT_NAME"
