import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import {
  displayEncounterText,
  displayItemText,
  displayStoryText,
} from "../src/lib/rpgContent/source";

const root = resolve(__dirname, "..");
const textOutPath = resolve(root, "src/lib/rpgContent/generatedText.ts");

const statIds = ["strength", "intellect", "agility", "spirit"] as const;

function renderGeneratedText() {
  return `${[
    "// @generated by scripts/generate_rpg_content.ts. Do not edit by hand.",
    "// Display text only. Rule-bearing content lives in contracts/src/content/data.cairo.",
    "",
    `export type TextStatId = ${statIds.map((stat) => JSON.stringify(stat)).join(" | ")};`,
    "",
    "export type EncounterOptionText = {",
    "  description: string;",
    "  label: string;",
    "};",
    "",
    "export type EncounterTextRecord = {",
    "  description: string;",
    "  id: string;",
    "  options: Record<TextStatId, EncounterOptionText>;",
    "  title: string;",
    "};",
    "",
    "export type ItemTextRecord = {",
    "  description: string;",
    "  id: string;",
    "  name: string;",
    "};",
    "",
    `export const storyText = ${JSON.stringify(displayStoryText, null, 2)} as const;`,
    "",
    `export const encounterText: Record<number, EncounterTextRecord> = ${JSON.stringify(displayEncounterText, null, 2)};`,
    "",
    `export const itemText: Record<number, ItemTextRecord> = ${JSON.stringify(displayItemText, null, 2)};`,
    "",
    "export type EncounterTextId = keyof typeof encounterText;",
    "export type ItemTextId = keyof typeof itemText;",
    "",
  ].join("\n")}`;
}

mkdirSync(dirname(textOutPath), { recursive: true });
writeFileSync(textOutPath, renderGeneratedText());

console.log(`Generated ${textOutPath}`);
