// @generated by scripts/generate_rpg_content.ts. Do not edit by hand.
// Display text only. Rule-bearing content lives in contracts/src/content/data.cairo.

export type TextStatId = "strength" | "intellect" | "agility" | "spirit";

export type EncounterOptionText = {
  description: string;
  label: string;
};

export type EncounterTextRecord = {
  description: string;
  id: string;
  options: Record<TextStatId, EncounterOptionText>;
  title: string;
};

export type ItemTextRecord = {
  description: string;
  id: string;
  name: string;
};

export const storyText = {
  "actIntros": {
    "1": {
      "description": "The first gate teaches the shape of the path. Build a direction, take early gear, and learn which problems suit your approach.",
      "title": "Act 1: The First Gate"
    },
    "2": {
      "description": "The road narrows after the Stone Warden. Your strongest stat should start feeling like a build, not just a preference.",
      "title": "Act 2: The Mirror Road"
    },
    "3": {
      "description": "The mountain asks whether your gear and choices agree. Strained checks will punish wandering builds.",
      "title": "Act 3: The Burning Pass"
    },
    "4": {
      "description": "The final ascent tests the identity you have made. Prepare for the last boss before the path stops giving room to recover.",
      "title": "Act 4: The Starward Gate"
    }
  },
  "bossDefeatedDescription": "A boss gate has fallen. Take a reward that strengthens the build that carried you here or covers the weakness the fight exposed.",
  "bossDefeatedTitle": "Boss defeated",
  "defeatDescription": "Your build could not carry you through this seed. Start again, specialize earlier, and let gear reinforce the stat that is winning checks.",
  "defeatTitle": "The road claims another challenger.",
  "intro": "The road is sealed. Choose your path and press onward.",
  "levelClearedDescription": "Review how the level went, then choose one item. Gear should either push your main stat toward the next boss or solve a slot weakness.",
  "levelClearedTitle": "Level cleared",
  "subtitle": "A dark path beyond the first gate.",
  "title": "Gravenhold",
  "victoryDescription": "The last gate opens because your choices formed a coherent path. This seed is complete; the build survived every boss check.",
  "victoryTitle": "The Crownless Star falls."
} as const;

export const encounterText: Record<number, EncounterTextRecord> = {
  "1": {
    "description": "A ruined gate blocks the road into the valley.",
    "id": "fixed_01_fallen_gate",
    "options": {
      "strength": {
        "description": "Lift the broken beam and shove the gate aside.",
        "label": "Force it open"
      },
      "intellect": {
        "description": "Find the weak hinge and loosen the frame.",
        "label": "Study the hinge"
      },
      "agility": {
        "description": "Slip through the warped bars before they settle.",
        "label": "Squeeze through"
      },
      "spirit": {
        "description": "Steady your breathing and push through the fear.",
        "label": "Hold steady"
      }
    },
    "title": "The Fallen Gate"
  },
  "2": {
    "description": "Cold rain turns the hillside path into sliding mud.",
    "id": "fixed_02_mudslide_path",
    "options": {
      "strength": {
        "description": "Drive your boots deep and pull yourself upward.",
        "label": "Climb hard"
      },
      "intellect": {
        "description": "Plot a safer route by reading the drainage lines.",
        "label": "Read the slope"
      },
      "agility": {
        "description": "Move lightly across stones before the slope gives way.",
        "label": "Step fast"
      },
      "spirit": {
        "description": "Keep your focus while the ground shifts underfoot.",
        "label": "Keep calm"
      }
    },
    "title": "Mudslide Path"
  },
  "3": {
    "description": "A nervous outpost guard demands proof you belong here.",
    "id": "fixed_03_border_guard",
    "options": {
      "strength": {
        "description": "Make it clear that blocking you is unwise.",
        "label": "Intimidate"
      },
      "intellect": {
        "description": "Answer with enough detail to sound expected.",
        "label": "Talk your way in"
      },
      "agility": {
        "description": "Move around the checkpoint while attention drifts.",
        "label": "Slip past"
      },
      "spirit": {
        "description": "Meet the guard's suspicion with unshaken confidence.",
        "label": "Stand firm"
      }
    },
    "title": "The Border Guard"
  },
  "4": {
    "description": "A stone marker hums with old instructions no one remembers.",
    "id": "fixed_04_speaking_marker",
    "options": {
      "strength": {
        "description": "Turn the heavy marker toward the road.",
        "label": "Rotate it"
      },
      "intellect": {
        "description": "Compare the symbols and infer their command order.",
        "label": "Decode it"
      },
      "agility": {
        "description": "Trace the shallow carved route with precise fingertips.",
        "label": "Trace the marks"
      },
      "spirit": {
        "description": "Listen for the intent beneath the marker's hum.",
        "label": "Attune"
      }
    },
    "title": "The Speaking Marker"
  },
  "5": {
    "description": "Scouts of the first guardian test everyone who approaches.",
    "id": "fixed_05_guardian_scouts",
    "options": {
      "strength": {
        "description": "Meet their charge with a direct counterattack.",
        "label": "Drive forward"
      },
      "intellect": {
        "description": "Identify their signal pattern and break their timing.",
        "label": "Read tactics"
      },
      "agility": {
        "description": "Draw them out of formation and strike the opening.",
        "label": "Outmaneuver"
      },
      "spirit": {
        "description": "Refuse their pressure and make them hesitate first.",
        "label": "Break resolve"
      }
    },
    "title": "Guardian Scouts"
  },
  "6": {
    "description": "A collapsed bridge hangs over a black ravine.",
    "id": "fixed_06_collapsed_bridge",
    "options": {
      "strength": {
        "description": "Move a fallen brace into place for a crossing.",
        "label": "Shift the brace"
      },
      "intellect": {
        "description": "Work out where the remaining structure still holds.",
        "label": "Find support"
      },
      "agility": {
        "description": "Leap from broken stone to broken stone.",
        "label": "Leap across"
      },
      "spirit": {
        "description": "Guide yourself across without looking down.",
        "label": "Master fear"
      }
    },
    "title": "Collapsed Bridge"
  },
  "7": {
    "description": "A sealed archive door opens only to a correct sequence.",
    "id": "fixed_07_archive_seal",
    "options": {
      "strength": {
        "description": "Hold the locking wheels in place as they turn.",
        "label": "Hold wheels"
      },
      "intellect": {
        "description": "Solve the sequence from the worn inscriptions.",
        "label": "Solve sequence"
      },
      "agility": {
        "description": "Press the sequence before the mechanism resets.",
        "label": "Move quickly"
      },
      "spirit": {
        "description": "Sense the pulse that marks the right order.",
        "label": "Feel the rhythm"
      }
    },
    "title": "Archive Seal"
  },
  "8": {
    "description": "A dust storm swallows the road and erases every landmark.",
    "id": "fixed_08_dust_storm",
    "options": {
      "strength": {
        "description": "Push forward with steady force through the storm.",
        "label": "Press on"
      },
      "intellect": {
        "description": "Navigate by wind direction and slope.",
        "label": "Calculate bearing"
      },
      "agility": {
        "description": "Keep low and move between gusts.",
        "label": "Thread the gusts"
      },
      "spirit": {
        "description": "Keep panic from turning each step into a mistake.",
        "label": "Center yourself"
      }
    },
    "title": "The Dust Storm"
  },
  "9": {
    "description": "A trapped caravan leader begs for help but hides something.",
    "id": "fixed_09_caravan_secret",
    "options": {
      "strength": {
        "description": "Take command and force the leader to stop stalling.",
        "label": "Demand truth"
      },
      "intellect": {
        "description": "Question the story until the missing piece appears.",
        "label": "Interrogate"
      },
      "agility": {
        "description": "Check the camp quietly before choosing what to believe.",
        "label": "Scout camp"
      },
      "spirit": {
        "description": "Read the fear beneath the lie and answer it directly.",
        "label": "Offer trust"
      }
    },
    "title": "The Caravan Secret"
  },
  "10": {
    "description": "Silent hunters guard the approach to the second gate.",
    "id": "fixed_10_silent_hunters",
    "options": {
      "strength": {
        "description": "Crash into the nearest hunter before they surround you.",
        "label": "Break line"
      },
      "intellect": {
        "description": "Use their shadows to reveal their positions.",
        "label": "Expose pattern"
      },
      "agility": {
        "description": "Keep moving so their ambush never settles.",
        "label": "Stay mobile"
      },
      "spirit": {
        "description": "Hold your nerve while they try to isolate you.",
        "label": "Resist pressure"
      }
    },
    "title": "Silent Hunters"
  },
  "11": {
    "description": "A cliff ladder of rusted spikes leads into the high pass.",
    "id": "fixed_11_spike_ladder",
    "options": {
      "strength": {
        "description": "Haul yourself up by brute force.",
        "label": "Pull upward"
      },
      "intellect": {
        "description": "Choose only the spikes that still carry weight.",
        "label": "Inspect spikes"
      },
      "agility": {
        "description": "Climb with quick, exact placements.",
        "label": "Climb cleanly"
      },
      "spirit": {
        "description": "Ignore the height and keep your grip steady.",
        "label": "Silence fear"
      }
    },
    "title": "Spike Ladder"
  },
  "12": {
    "description": "Mirrors in an old hall show different versions of the path.",
    "id": "fixed_12_mirror_hall",
    "options": {
      "strength": {
        "description": "Shatter the mirrors that press closest.",
        "label": "Smash through"
      },
      "intellect": {
        "description": "Find the one reflection that obeys real light.",
        "label": "Test reflections"
      },
      "agility": {
        "description": "Move only when the false reflections lag behind.",
        "label": "Time movement"
      },
      "spirit": {
        "description": "Hold to your own identity until the hall releases you.",
        "label": "Anchor self"
      }
    },
    "title": "Mirror Hall"
  },
  "13": {
    "description": "Poisoned mist rises from cracked vents in the pass.",
    "id": "fixed_13_venom_mist",
    "options": {
      "strength": {
        "description": "Block vents with loose stone as you advance.",
        "label": "Seal vents"
      },
      "intellect": {
        "description": "Track the vent pattern and mark a clean route.",
        "label": "Map vents"
      },
      "agility": {
        "description": "Dash between clear pockets before they close.",
        "label": "Sprint gaps"
      },
      "spirit": {
        "description": "Slow your breath and resist the mist's panic.",
        "label": "Control breath"
      }
    },
    "title": "Venom Mist"
  },
  "14": {
    "description": "A divided camp argues over whether to let you pass.",
    "id": "fixed_14_divided_camp",
    "options": {
      "strength": {
        "description": "Make one clear demand and hold the center.",
        "label": "Take command"
      },
      "intellect": {
        "description": "Offer a solution both sides can accept.",
        "label": "Mediate"
      },
      "agility": {
        "description": "Move through the argument before anyone blocks you.",
        "label": "Slip through"
      },
      "spirit": {
        "description": "Speak to the fear driving the camp apart.",
        "label": "Inspire trust"
      }
    },
    "title": "The Divided Camp"
  },
  "15": {
    "description": "The third guardian's vanguard blocks the mountain gate.",
    "id": "fixed_15_mountain_vanguard",
    "options": {
      "strength": {
        "description": "Break the shield line with a direct assault.",
        "label": "Crack shields"
      },
      "intellect": {
        "description": "Draw the vanguard into exposing its captain.",
        "label": "Bait captain"
      },
      "agility": {
        "description": "Cut through the flank before the line turns.",
        "label": "Strike flank"
      },
      "spirit": {
        "description": "Stand against their chant until it falters.",
        "label": "Defy chant"
      }
    },
    "title": "Mountain Vanguard"
  },
  "16": {
    "description": "A frozen stair climbs through thin air and falling ice.",
    "id": "fixed_16_frozen_stair",
    "options": {
      "strength": {
        "description": "Cut footholds into the ice as you climb.",
        "label": "Hack footholds"
      },
      "intellect": {
        "description": "Choose a path where the ice is oldest and strongest.",
        "label": "Read ice"
      },
      "agility": {
        "description": "Cross the slick steps before frost grips your boots.",
        "label": "Move lightly"
      },
      "spirit": {
        "description": "Keep warmth in your limbs through force of will.",
        "label": "Hold warmth"
      }
    },
    "title": "Frozen Stair"
  },
  "17": {
    "description": "A locked observatory turns with the stars above.",
    "id": "fixed_17_star_observatory",
    "options": {
      "strength": {
        "description": "Hold the rotating mechanism in place.",
        "label": "Brace gears"
      },
      "intellect": {
        "description": "Align the lenses to the correct constellation.",
        "label": "Align stars"
      },
      "agility": {
        "description": "Reach the moving controls before the window passes.",
        "label": "Catch controls"
      },
      "spirit": {
        "description": "Follow the pull of the star that watches you back.",
        "label": "Follow omen"
      }
    },
    "title": "Star Observatory"
  },
  "18": {
    "description": "The path narrows beside a storm that climbs upward.",
    "id": "fixed_18_upward_storm",
    "options": {
      "strength": {
        "description": "Anchor yourself and advance one step at a time.",
        "label": "Anchor forward"
      },
      "intellect": {
        "description": "Predict the storm's rhythm from its echoes.",
        "label": "Predict rhythm"
      },
      "agility": {
        "description": "Step between lightning strikes and sudden gusts.",
        "label": "Dodge storm"
      },
      "spirit": {
        "description": "Refuse the storm's pull and keep your purpose clear.",
        "label": "Hold purpose"
      }
    },
    "title": "The Upward Storm"
  },
  "19": {
    "description": "The last pilgrims ask why you deserve the final road.",
    "id": "fixed_19_last_pilgrims",
    "options": {
      "strength": {
        "description": "Show that you can carry the burden ahead.",
        "label": "Bear weight"
      },
      "intellect": {
        "description": "Explain the pattern that brought you this far.",
        "label": "Make your case"
      },
      "agility": {
        "description": "Show the speed and precision your journey has forged.",
        "label": "Demonstrate skill"
      },
      "spirit": {
        "description": "Answer with conviction rather than argument.",
        "label": "Speak truth"
      }
    },
    "title": "The Last Pilgrims"
  },
  "20": {
    "description": "The final gate gathers every trial into one last warning.",
    "id": "fixed_20_final_gate",
    "options": {
      "strength": {
        "description": "Force the gate to acknowledge your arrival.",
        "label": "Open by force"
      },
      "intellect": {
        "description": "Recognize the trials' shared structure and open the way.",
        "label": "Solve pattern"
      },
      "agility": {
        "description": "Move through the shifting defenses before they lock.",
        "label": "Pass defenses"
      },
      "spirit": {
        "description": "Stand whole before the pressure of the final gate.",
        "label": "Remain whole"
      }
    },
    "title": "The Final Gate"
  },
  "101": {
    "description": "Road raiders move in when they think you are tired.",
    "id": "random_road_raiders",
    "options": {
      "strength": {
        "description": "Hit first and make the rest reconsider.",
        "label": "Hit first"
      },
      "intellect": {
        "description": "Turn their impatience into a bad formation.",
        "label": "Set trap"
      },
      "agility": {
        "description": "Circle away from their strongest attacker.",
        "label": "Circle out"
      },
      "spirit": {
        "description": "Refuse to show fear and make them doubt the attack.",
        "label": "Hold nerve"
      }
    },
    "title": "Road Raiders"
  },
  "102": {
    "description": "A locked service door promises a shorter route.",
    "id": "random_locked_service_door",
    "options": {
      "strength": {
        "description": "Break the latch without slowing down.",
        "label": "Break latch"
      },
      "intellect": {
        "description": "Infer the key pattern from scratched marks.",
        "label": "Read marks"
      },
      "agility": {
        "description": "Pick the lock with careful pressure.",
        "label": "Pick lock"
      },
      "spirit": {
        "description": "Wait until instinct points to the right moment.",
        "label": "Trust instinct"
      }
    },
    "title": "Locked Service Door"
  },
  "103": {
    "description": "A whispering shrine offers advice in exchange for focus.",
    "id": "random_whispering_shrine",
    "options": {
      "strength": {
        "description": "Move the altar stone into its old position.",
        "label": "Move altar"
      },
      "intellect": {
        "description": "Separate useful clues from ritual noise.",
        "label": "Parse whispers"
      },
      "agility": {
        "description": "Catch the shrine's shifting light before it fades.",
        "label": "Catch light"
      },
      "spirit": {
        "description": "Open yourself to the shrine without losing control.",
        "label": "Commune"
      }
    },
    "title": "Whispering Shrine"
  },
  "104": {
    "description": "A night without shelter threatens to drain your momentum.",
    "id": "random_exposed_night",
    "options": {
      "strength": {
        "description": "Carry stones and branches into a sturdy camp.",
        "label": "Build camp"
      },
      "intellect": {
        "description": "Build a windbreak from what the trail provides.",
        "label": "Rig shelter"
      },
      "agility": {
        "description": "Find a narrow dry place before the cold settles.",
        "label": "Find cover"
      },
      "spirit": {
        "description": "Rest despite discomfort and keep despair away.",
        "label": "Endure night"
      }
    },
    "title": "Exposed Night"
  },
  "105": {
    "description": "A suspicious scout watches from the tree line.",
    "id": "random_suspicious_scout",
    "options": {
      "strength": {
        "description": "Show enough force to end the scout's confidence.",
        "label": "Display force"
      },
      "intellect": {
        "description": "Offer information that proves you are no easy mark.",
        "label": "Trade facts"
      },
      "agility": {
        "description": "Vanish from sight and approach from a better angle.",
        "label": "Disappear"
      },
      "spirit": {
        "description": "Meet suspicion with honest calm.",
        "label": "Show calm"
      }
    },
    "title": "Suspicious Scout"
  },
  "106": {
    "description": "A fallen pillar pins a narrow passage shut.",
    "id": "random_fallen_pillar",
    "options": {
      "strength": {
        "description": "Lift the pillar just enough to pass.",
        "label": "Lift pillar"
      },
      "intellect": {
        "description": "Find the leverage point that matters.",
        "label": "Find leverage"
      },
      "agility": {
        "description": "Slide through the lowest gap without getting trapped.",
        "label": "Slide under"
      },
      "spirit": {
        "description": "Keep patient while dust and pressure close in.",
        "label": "Stay patient"
      }
    },
    "title": "Fallen Pillar"
  },
  "107": {
    "description": "A lean beast stalks the trail from above.",
    "id": "random_stalking_beast",
    "options": {
      "strength": {
        "description": "Meet the pounce with a brutal counter.",
        "label": "Counterattack"
      },
      "intellect": {
        "description": "Use its hunting pattern against it.",
        "label": "Predict pounce"
      },
      "agility": {
        "description": "Dodge the first pounce and strike the exposed side.",
        "label": "Dodge pounce"
      },
      "spirit": {
        "description": "Hold eye contact until it breaks first.",
        "label": "Face it down"
      }
    },
    "title": "Stalking Beast"
  },
  "108": {
    "description": "An old map contradicts the road beneath your feet.",
    "id": "random_false_map",
    "options": {
      "strength": {
        "description": "Cut through the blocked direct path.",
        "label": "Clear route"
      },
      "intellect": {
        "description": "Spot where the mapmaker deliberately lied.",
        "label": "Find lie"
      },
      "agility": {
        "description": "Scout both branches before committing.",
        "label": "Scout branches"
      },
      "spirit": {
        "description": "Choose the path that feels least corrupted.",
        "label": "Trust pull"
      }
    },
    "title": "False Map"
  },
  "109": {
    "description": "A sudden flood cuts across the low road.",
    "id": "random_flash_flood",
    "options": {
      "strength": {
        "description": "Push through the current before it deepens.",
        "label": "Wade through"
      },
      "intellect": {
        "description": "Find where the current loses strength.",
        "label": "Read current"
      },
      "agility": {
        "description": "Hop across debris before it drifts apart.",
        "label": "Cross debris"
      },
      "spirit": {
        "description": "Move without panic while the water rises.",
        "label": "Stay composed"
      }
    },
    "title": "Flash Flood"
  },
  "110": {
    "description": "A wounded messenger asks for aid but delays your route.",
    "id": "random_wounded_messenger",
    "options": {
      "strength": {
        "description": "Carry the messenger to safety yourself.",
        "label": "Carry them"
      },
      "intellect": {
        "description": "Extract the critical information before time is lost.",
        "label": "Assess message"
      },
      "agility": {
        "description": "Carry the message ahead and return by a faster path.",
        "label": "Run message"
      },
      "spirit": {
        "description": "Stabilize the messenger and restore their courage.",
        "label": "Comfort"
      }
    },
    "title": "Wounded Messenger"
  },
  "111": {
    "description": "A shield patrol blocks the road and waits for you to make the first mistake.",
    "id": "random_shield_patrol",
    "options": {
      "strength": {
        "description": "Drive into the wall and force a gap.",
        "label": "Split shields"
      },
      "intellect": {
        "description": "Call out the captain's weak command and break formation.",
        "label": "Break orders"
      },
      "agility": {
        "description": "Slip around the shield wall before it closes.",
        "label": "Flank wall"
      },
      "spirit": {
        "description": "Meet their discipline with steadier resolve.",
        "label": "Outlast pressure"
      }
    },
    "title": "Shield Patrol"
  },
  "112": {
    "description": "A tunnel crawler drops from the ceiling with hooked claws.",
    "id": "random_tunnel_crawler",
    "options": {
      "strength": {
        "description": "Catch the creature's weight and slam it down.",
        "label": "Slam it"
      },
      "intellect": {
        "description": "Use the scrape marks to predict its next drop.",
        "label": "Read scrapes"
      },
      "agility": {
        "description": "Roll clear and strike before it turns.",
        "label": "Roll under"
      },
      "spirit": {
        "description": "Hold still long enough to make it reveal itself.",
        "label": "Master panic"
      }
    },
    "title": "Tunnel Crawler"
  },
  "113": {
    "description": "A bandit archer controls the ridge above the trail.",
    "id": "random_ridge_archer",
    "options": {
      "strength": {
        "description": "Raise a broken panel and push forward behind it.",
        "label": "Carry shield"
      },
      "intellect": {
        "description": "Count the firing rhythm and move during the reload.",
        "label": "Time reload"
      },
      "agility": {
        "description": "Sprint between shots and reach the ridge.",
        "label": "Rush cover"
      },
      "spirit": {
        "description": "Walk through the threat without giving fear a foothold.",
        "label": "Steady advance"
      }
    },
    "title": "Ridge Archer"
  },
  "114": {
    "description": "A swarm of ember mites pours from a cracked brazier.",
    "id": "random_ember_mites",
    "options": {
      "strength": {
        "description": "Smother the brazier under fallen stone.",
        "label": "Crush brazier"
      },
      "intellect": {
        "description": "Starve the swarm by sealing its warmest vents.",
        "label": "Seal vents"
      },
      "agility": {
        "description": "Step through the swarm where it thins.",
        "label": "Thread swarm"
      },
      "spirit": {
        "description": "Quiet the frantic heat until the swarm scatters.",
        "label": "Soothe flame"
      }
    },
    "title": "Ember Mites"
  },
  "115": {
    "description": "A chain lift hangs jammed between two floors of the ruin.",
    "id": "random_jammed_chain_lift",
    "options": {
      "strength": {
        "description": "Pull the lift level by raw effort.",
        "label": "Haul lift"
      },
      "intellect": {
        "description": "Release the right catch without dropping the platform.",
        "label": "Free catch"
      },
      "agility": {
        "description": "Climb the side chain before the lift slips.",
        "label": "Climb chain"
      },
      "spirit": {
        "description": "Keep the trapped travelers calm while the lift groans.",
        "label": "Calm lift"
      }
    },
    "title": "Jammed Chain Lift"
  },
  "116": {
    "description": "A hall of pressure plates waits under a skin of dust.",
    "id": "random_pressure_plate_hall",
    "options": {
      "strength": {
        "description": "Brace the trigger stones before crossing.",
        "label": "Jam plates"
      },
      "intellect": {
        "description": "Map the safe plates from their spacing.",
        "label": "Map plates"
      },
      "agility": {
        "description": "Cross on the narrow safe edges.",
        "label": "Edge step"
      },
      "spirit": {
        "description": "Trust one clean rhythm and do not hesitate.",
        "label": "Keep rhythm"
      }
    },
    "title": "Pressure Plate Hall"
  },
  "117": {
    "description": "A root-choked stair twists down into darkness.",
    "id": "random_root_choked_stair",
    "options": {
      "strength": {
        "description": "Tear open a usable stairway.",
        "label": "Rip path"
      },
      "intellect": {
        "description": "Find where the roots avoid old ward lines.",
        "label": "Trace wards"
      },
      "agility": {
        "description": "Duck and weave through the living knots.",
        "label": "Weave roots"
      },
      "spirit": {
        "description": "Ask the roots for passage without surrendering direction.",
        "label": "Ask passage"
      }
    },
    "title": "Root-Choked Stair"
  },
  "118": {
    "description": "A cracked aqueduct spills water across a narrow ledge.",
    "id": "random_spilling_aqueduct",
    "options": {
      "strength": {
        "description": "Hold a fallen slab against the torrent.",
        "label": "Hold slab"
      },
      "intellect": {
        "description": "Redirect the spill through a lower channel.",
        "label": "Redirect flow"
      },
      "agility": {
        "description": "Cross the slick ledge in one committed burst.",
        "label": "Burst across"
      },
      "spirit": {
        "description": "Keep your balance by focusing past the roar.",
        "label": "Hear silence"
      }
    },
    "title": "Spilling Aqueduct"
  },
  "119": {
    "description": "A door repeats your last words and waits for a truer answer.",
    "id": "random_echo_door",
    "options": {
      "strength": {
        "description": "Hold the door half-open against the echo's pull.",
        "label": "Hold open"
      },
      "intellect": {
        "description": "Phrase the answer so the echo completes the key.",
        "label": "Shape answer"
      },
      "agility": {
        "description": "Catch the door's latch during the echo delay.",
        "label": "Catch latch"
      },
      "spirit": {
        "description": "Speak with enough conviction that the echo stops arguing.",
        "label": "Speak true"
      }
    },
    "title": "Echo Door"
  },
  "120": {
    "description": "A mural changes whenever you look directly at it.",
    "id": "random_shifting_mural",
    "options": {
      "strength": {
        "description": "Press the mural panels into their original alignment.",
        "label": "Set panels"
      },
      "intellect": {
        "description": "Compare each version and isolate the constant symbol.",
        "label": "Find constant"
      },
      "agility": {
        "description": "Move across the room while reading it from the corner of your eye.",
        "label": "Read sidelong"
      },
      "spirit": {
        "description": "Let the image settle into the meaning it wants to show.",
        "label": "Let settle"
      }
    },
    "title": "Shifting Mural"
  },
  "121": {
    "description": "A bronze compass spins toward dangers you cannot see.",
    "id": "random_bronze_compass",
    "options": {
      "strength": {
        "description": "Hold the compass steady long enough to read it.",
        "label": "Hold steady"
      },
      "intellect": {
        "description": "Infer the hidden hazards from the needle's pattern.",
        "label": "Infer hazards"
      },
      "agility": {
        "description": "Move each time the needle twitches away from you.",
        "label": "Follow twitches"
      },
      "spirit": {
        "description": "Quiet the compass until it points at intent, not fear.",
        "label": "Quiet needle"
      }
    },
    "title": "Bronze Compass"
  },
  "122": {
    "description": "A library ladder rolls by itself between sealed shelves.",
    "id": "random_restless_ladder",
    "options": {
      "strength": {
        "description": "Pin the ladder rails and force it to stop.",
        "label": "Pin rails"
      },
      "intellect": {
        "description": "Name the shelf sequence that controls its route.",
        "label": "Name sequence"
      },
      "agility": {
        "description": "Leap to the ladder before it escapes again.",
        "label": "Leap aboard"
      },
      "spirit": {
        "description": "Convince the old mechanism that you mean no theft.",
        "label": "Offer intent"
      }
    },
    "title": "Restless Ladder"
  },
  "123": {
    "description": "Thin mountain air makes each step cost more than it should.",
    "id": "random_thin_air",
    "options": {
      "strength": {
        "description": "Push through with slow and stubborn force.",
        "label": "Push onward"
      },
      "intellect": {
        "description": "Set a pace that keeps breath and slope aligned.",
        "label": "Set pace"
      },
      "agility": {
        "description": "Use short, efficient bursts between rests.",
        "label": "Burst climb"
      },
      "spirit": {
        "description": "Hold your focus while your body begs to stop.",
        "label": "Hold focus"
      }
    },
    "title": "Thin Air"
  },
  "124": {
    "description": "A field of glass grass cuts boots, gloves, and patience.",
    "id": "random_glass_grass",
    "options": {
      "strength": {
        "description": "Sweep a path with a heavy branch.",
        "label": "Sweep path"
      },
      "intellect": {
        "description": "Mark the safe path by how the glass reflects sky.",
        "label": "Read shine"
      },
      "agility": {
        "description": "Step only where the blades bend away.",
        "label": "Step clean"
      },
      "spirit": {
        "description": "Move without anger while each cut tries to distract you.",
        "label": "Ignore cuts"
      }
    },
    "title": "Glass Grass"
  },
  "125": {
    "description": "A hungry fog steals direction and sound from the pass.",
    "id": "random_hungry_fog",
    "options": {
      "strength": {
        "description": "Carry a ringing post and force a straight line.",
        "label": "Drive line"
      },
      "intellect": {
        "description": "Use echoes and slope to reconstruct the road.",
        "label": "Track echoes"
      },
      "agility": {
        "description": "Move quickly between the last visible landmarks.",
        "label": "Dash marks"
      },
      "spirit": {
        "description": "Refuse the fog's whispering invitations.",
        "label": "Deny whispers"
      }
    },
    "title": "Hungry Fog"
  },
  "126": {
    "description": "A sinkhole opens beneath the camp before dawn.",
    "id": "random_dawn_sinkhole",
    "options": {
      "strength": {
        "description": "Drag the loaded pack out before it disappears.",
        "label": "Drag pack"
      },
      "intellect": {
        "description": "Spot the stable rim before the ground drops again.",
        "label": "Find rim"
      },
      "agility": {
        "description": "Jump clear and pull your gear after you.",
        "label": "Jump clear"
      },
      "spirit": {
        "description": "Keep everyone responding instead of freezing.",
        "label": "Rally camp"
      }
    },
    "title": "Dawn Sinkhole"
  },
  "127": {
    "description": "A toll keeper demands payment in secrets instead of coins.",
    "id": "random_secret_toll",
    "options": {
      "strength": {
        "description": "Make the keeper decide the price is not worth collecting.",
        "label": "Deter keeper"
      },
      "intellect": {
        "description": "Offer a harmless secret that sounds valuable enough.",
        "label": "Trade riddle"
      },
      "agility": {
        "description": "Slip through while the keeper records another traveler's answer.",
        "label": "Slip toll"
      },
      "spirit": {
        "description": "Refuse the bargain without provoking the keeper.",
        "label": "Refuse calmly"
      }
    },
    "title": "Secret Toll"
  },
  "128": {
    "description": "A frightened apprentice mistakes you for the threat they fled.",
    "id": "random_frightened_apprentice",
    "options": {
      "strength": {
        "description": "Stand between them and the road until they feel protected.",
        "label": "Guard them"
      },
      "intellect": {
        "description": "Ask precise questions that prove you know the difference.",
        "label": "Question gently"
      },
      "agility": {
        "description": "Keep distance and move where your hands stay visible.",
        "label": "Keep distance"
      },
      "spirit": {
        "description": "Lower their panic before it turns into danger.",
        "label": "Ease panic"
      }
    },
    "title": "Frightened Apprentice"
  },
  "129": {
    "description": "Two rival guides each insist the other path is a trap.",
    "id": "random_rival_guides",
    "options": {
      "strength": {
        "description": "Take responsibility for the decision and make them follow.",
        "label": "Lead decisively"
      },
      "intellect": {
        "description": "Compare their details until one story breaks.",
        "label": "Compare claims"
      },
      "agility": {
        "description": "Scout both paths before either guide can object.",
        "label": "Scout both"
      },
      "spirit": {
        "description": "Find the fear both guides are hiding behind pride.",
        "label": "Name fear"
      }
    },
    "title": "Rival Guides"
  },
  "130": {
    "description": "A silent judge bars the stair and weighs every gesture.",
    "id": "random_silent_judge",
    "options": {
      "strength": {
        "description": "Lift the trial weight and hold it without complaint.",
        "label": "Hold weight"
      },
      "intellect": {
        "description": "Present the cleanest argument for your passage.",
        "label": "State case"
      },
      "agility": {
        "description": "Make one flawless movement that proves discipline.",
        "label": "Show precision"
      },
      "spirit": {
        "description": "Stand honestly beneath the judge's attention.",
        "label": "Stand honest"
      }
    },
    "title": "Silent Judge"
  },
  "201": {
    "description": "The Stone Warden blocks the first gate with a body of carved granite.",
    "id": "boss_05_stone_warden",
    "options": {
      "strength": {
        "description": "Shatter its armor with repeated heavy strikes.",
        "label": "Shatter armor"
      },
      "intellect": {
        "description": "Read the command marks and disrupt its control pattern.",
        "label": "Break pattern"
      },
      "agility": {
        "description": "Move between its slow attacks and strike exposed joints.",
        "label": "Strike joints"
      },
      "spirit": {
        "description": "Resist its fear aura and weaken the binding magic.",
        "label": "Resist aura"
      }
    },
    "title": "The Stone Warden"
  },
  "202": {
    "description": "The Glass Regent reflects every hesitation back as a sharper threat.",
    "id": "boss_10_glass_regent",
    "options": {
      "strength": {
        "description": "Break the mirror shell before it multiplies again.",
        "label": "Break shell"
      },
      "intellect": {
        "description": "Identify the true body among the false images.",
        "label": "Find true form"
      },
      "agility": {
        "description": "Move faster than the reflections can correct.",
        "label": "Outpace mirrors"
      },
      "spirit": {
        "description": "Hold your identity while the reflections try to split it.",
        "label": "Remain whole"
      }
    },
    "title": "The Glass Regent"
  },
  "203": {
    "description": "The Ash Titan waits where the mountain burns from within.",
    "id": "boss_15_ash_titan",
    "options": {
      "strength": {
        "description": "Meet its crushing blows until its stance fails.",
        "label": "Break stance"
      },
      "intellect": {
        "description": "Turn the vents beneath it into a trap.",
        "label": "Reroute vents"
      },
      "agility": {
        "description": "Strike during the small openings between eruptions.",
        "label": "Thread eruptions"
      },
      "spirit": {
        "description": "Withstand the heat and deny its command of fear.",
        "label": "Defy flame"
      }
    },
    "title": "The Ash Titan"
  },
  "204": {
    "description": "The Crownless Star tests the shape your choices have made.",
    "id": "boss_20_crownless_star",
    "options": {
      "strength": {
        "description": "Carry the full weight of the path and force an ending.",
        "label": "Force ending"
      },
      "intellect": {
        "description": "Solve the final pattern hidden across every prior trial.",
        "label": "Solve final law"
      },
      "agility": {
        "description": "Move through impossible angles and strike the opening.",
        "label": "Cross angles"
      },
      "spirit": {
        "description": "Stand as yourself against the pressure of the star.",
        "label": "Hold self"
      }
    },
    "title": "The Crownless Star"
  }
};

export const itemText: Record<number, ItemTextRecord> = {
  "1": {
    "description": "Iron plates fitted for direct force.",
    "id": "iron_gauntlets",
    "name": "Iron Gauntlets"
  },
  "2": {
    "description": "A ring etched with patient mnemonic marks.",
    "id": "scholar_ring",
    "name": "Scholar Ring"
  },
  "3": {
    "description": "Soft boots built for quiet footing.",
    "id": "shadow_boots",
    "name": "Shadow Boots"
  },
  "4": {
    "description": "A warm charm that steadies breath under pressure.",
    "id": "ember_charm",
    "name": "Ember Charm"
  },
  "5": {
    "description": "A practical cloak with hidden pockets and map-stitching.",
    "id": "balanced_cloak",
    "name": "Balanced Cloak"
  },
  "6": {
    "description": "A heavy cord worn by those who refuse to yield.",
    "id": "oath_cord",
    "name": "Oath Cord"
  },
  "7": {
    "description": "A blunt blade made for breaking guards and gates.",
    "id": "breaker_blade",
    "name": "Breaker Blade"
  },
  "8": {
    "description": "A narrow lens that reveals stress lines and hidden joins.",
    "id": "logic_lens",
    "name": "Logic Lens"
  },
  "9": {
    "description": "Light armor that turns sudden movement into protection.",
    "id": "quickstep_vest",
    "name": "Quickstep Vest"
  },
  "10": {
    "description": "A polished icon that stays warm in hostile places.",
    "id": "resolve_icon",
    "name": "Resolve Icon"
  },
  "11": {
    "description": "A fitted mail shirt with marked reinforcement points.",
    "id": "engineer_mail",
    "name": "Engineer Mail"
  },
  "12": {
    "description": "A pendant that helps its bearer move without panic.",
    "id": "wind_prayer",
    "name": "Wind Prayer"
  },
  "13": {
    "description": "A war hammer balanced for relentless pressure.",
    "id": "warden_hammer",
    "name": "Warden Hammer"
  },
  "14": {
    "description": "A traveling codex of methods, proofs, and countersigns.",
    "id": "living_codex",
    "name": "Living Codex"
  },
  "15": {
    "description": "A mantle that seems to choose the easiest path first.",
    "id": "mist_mantle",
    "name": "Mist Mantle"
  },
  "16": {
    "description": "A relic that quiets fear before it can take shape.",
    "id": "lantern_relic",
    "name": "Lantern Relic"
  },
  "17": {
    "description": "A precise dueling weapon with unexpected stopping power.",
    "id": "duelist_knife",
    "name": "Duelist Knife"
  },
  "18": {
    "description": "A silver circlet for calm judgment under supernatural pressure.",
    "id": "sage_circlet",
    "name": "Sage Circlet"
  },
  "19": {
    "description": "A legendary edge that answers only decisive force.",
    "id": "titan_edge",
    "name": "Titan Edge"
  },
  "20": {
    "description": "A crystal archive that assembles patterns as they appear.",
    "id": "oracle_prism",
    "name": "Oracle Prism"
  },
  "21": {
    "description": "A seamless coat that never catches, drags, or hesitates.",
    "id": "horizon_coat",
    "name": "Horizon Coat"
  },
  "22": {
    "description": "An old star set in iron, still bright in the dark.",
    "id": "star_heart",
    "name": "Star Heart"
  },
  "23": {
    "description": "A weapon whose weight changes when its bearer understands it.",
    "id": "calculated_maul",
    "name": "Calculated Maul"
  },
  "24": {
    "description": "Armor built for motion guided by instinct.",
    "id": "moonstep_armor",
    "name": "Moonstep Armor"
  },
  "25": {
    "description": "A battered guard plate that turns the shoulder into a weapon.",
    "id": "guard_buckler",
    "name": "Guard Buckler"
  },
  "26": {
    "description": "A writing blade used to mark plans into wood, wax, and stone.",
    "id": "cipher_quill",
    "name": "Cipher Quill"
  },
  "27": {
    "description": "A narrow dagger balanced for one clean opening.",
    "id": "foxglass_dagger",
    "name": "Foxglass Dagger"
  },
  "28": {
    "description": "A plain travel mantle that keeps fear from spreading.",
    "id": "pilgrim_mantle",
    "name": "Pilgrim Mantle"
  },
  "29": {
    "description": "Layered plates built for holding ground under impact.",
    "id": "bulwark_plate",
    "name": "Bulwark Plate"
  },
  "30": {
    "description": "A command rod marked with battlefield timing notes.",
    "id": "tactician_baton",
    "name": "Tactician Baton"
  },
  "31": {
    "description": "A hooked blade that rewards quick angles and clean exits.",
    "id": "glasshook_blade",
    "name": "Glasshook Blade"
  },
  "32": {
    "description": "Quiet mail that turns each breath into renewed commitment.",
    "id": "vowkeeper_mail",
    "name": "Vowkeeper Mail"
  },
  "33": {
    "description": "A heavy harness that lets the whole body answer a challenge.",
    "id": "giantbone_harness",
    "name": "Giantbone Harness"
  },
  "34": {
    "description": "A scepter whose etched head preserves solved patterns.",
    "id": "pattern_scepter",
    "name": "Pattern Scepter"
  },
  "35": {
    "description": "Twin climbing blades that make vertical routes feel level.",
    "id": "skycutters",
    "name": "Skycutters"
  },
  "36": {
    "description": "A polished breastplate carried by those who refuse despair.",
    "id": "saints_aegis",
    "name": "Saint's Aegis"
  },
  "37": {
    "description": "A mantle weighted like a mountain and cut for those who can bear it.",
    "id": "worldbreak_mantle",
    "name": "Worldbreak Mantle"
  },
  "38": {
    "description": "A staff that turns final assumptions into visible structure.",
    "id": "final_theorem_staff",
    "name": "Final Theorem Staff"
  },
  "39": {
    "description": "A needle blade that finds the space before an opening exists.",
    "id": "phantom_needle",
    "name": "Phantom Needle"
  },
  "40": {
    "description": "A bright plate harness that makes retreat feel impossible.",
    "id": "dawnward_plate",
    "name": "Dawnward Plate"
  }
};

export type EncounterTextId = keyof typeof encounterText;
export type ItemTextId = keyof typeof itemText;
